### ISSUE TITLE
Unable to install or startup project.

### ISSUE THREAD

**Issue by DarkStar1** [auth0/auth0-angular2#1]
I cloned and first ran into the issue that npm couldn't find the JWT dependency, got past that, then it couldn't install gulp; got past that and now it complans about:  Error: Cannot find module 'gulp-typescript'
As a beginner these are hurdles that aren't obvious from the instructions on the project and require time spent googling to resolve these issues.

**Comment by chenkie** [comment]
Sorry for the delay. Things were in flux a bit but should be working now. You can check out [this post](https://auth0.com/blog/2015/11/10/introducing-angular2-jwt-a-library-for-angular2-authentication/) on how to get up and running :)
