### ISSUE TITLE
TS2304: Cannot find name 'Auth0Lock'.

### ISSUE THREAD

**Issue by choopage** [auth0/auth0-angular2#12]
Hi Ryan @chenkie 

I have this error `TS2304: Cannot find name 'Auth0Lock'.` when trying to implement Auth0 by following your tutorial. 
My repo is available at https://github.com/choopage/auth0-angular2-webpack

![screen shot 2016-01-31 at 11 49 55 am](https://cloud.githubusercontent.com/assets/6467136/12700140/8ad6086c-c811-11e5-9e78-6de2d0c48e7b.png)

**Comment by chenkie** [comment]
Hi @choopage!

Did you declare `Auth0Lock`? If you put this below your imports in `app.ts`, it should get ride of it:

```js
declare var Auth0Lock;
```

Let me know if that works.

**Comment by choopage** [comment]
Hi @chenkie 

It worked after declaring the variable Auth0Lock. Thanks for your assistance. 

1. From my observation by doing `declare var Auth0Lock` we are telling TypeScript "hey the variable Auth0Lock is available in the js" of `<script src="//cdn.auth0.com/js/lock-8.1.min.js"></script>`. Is my observation correct? 
_(trying to learn something out of my mistake)_

2. Before submitting an issue for this, I followed closely the tutorials on Auth0.com. I didn't come across this piece of code `declare var Auth0Lock`. Could you point me to the documentation that has this? Perhaps I might have missed some important information that I want to follow-up. 

Look forward to hearing from you soon :+1:

**Comment by chenkie** [comment]
You bet, declaring it lets TypeScript know that its there as a global.

It's there in the sample projects in this repo, but I just realized its not in the official doc. I'll make sure to add it there, thanks for the heads up!

**Comment by nukkerone** [comment]
Doesn't work for me.  Im adding the var declaration:

`declare var Auth0Lock: any;`

When I take a look at the compiled file app.bundled.js, there is not reference to that declaration, and thus getting a reference exception when running in the simulator:

`Can't find variable Auth0Lock`

**Comment by Quixotical** [comment]
I have the same issue as @nukkerone

**Comment by littledumb** [comment]
use `<script src="https://cdn.auth0.com/js/lock/10.8/lock.min.js"></script>` instead of `npm install --save auth0-lock`

@nukkerone @Quixotical
