### ISSUE TITLE
Seed projects dont read credentials from auth0-variables.js file

### ISSUE THREAD

**Issue by Annyv2** [auth0/auth0-angular2#15]
When downloading the seed project from auth0.com, it creates a file called auth0-variables.js that has Auth0 credentials on it, but these credentials are not used in the seed projects, so they have to be manually changed in the app.ts file

**Comment by chenkie** [comment]
This one is tougher to solve right now with the build steps involved in the sub-directories. Will wait for overall `auth0-variables` improvements before changing this.
