### ISSUE TITLE
The page sometimes does not refresh after logging in (still see the Login button after successful login)

### ISSUE THREAD

**Issue by ababkin** [auth0/auth0-angular2#19]
Try logging in by entering credentials and clicking the round submit button and not 'enter' after typing in the password.
Also, if you logout from one account, then login with a different set of credentials, the page does not refresh

Tried this on both Chrome and Opera

**Comment by chenkie** [comment]
This seems to be an issue with popup mode not causing the app to trigger change detection. An alternative is to use redirect mode instead of popup mode. Take a look at this repo to see how that can be implemented: https://github.com/auth0-blog/angular2-tour-of-heroes

**Comment by deanpeterson** [comment]
One of the main reasons we would like to use Auth0 is the popup mode rather than the redirect mode.  We are running into the same issue evaluating Auth0 with Angular2.  Is there a fix for this coming or can  you direct us how we might make changes to get around this for now?

**Comment by chenkie** [comment]
I've got some updated examples coming shortly :)

**Comment by deanpeterson** [comment]
That was a very fast reply :)  Awesome, can't wait to see them!

**Comment by chenkie** [comment]
Just pushed the updated examples.

Using `NgZone` to trigger view updates is how we can solve this issue. Checkout the `auth.service.ts` file in either project to see how it's implemented :)
