### ISSUE TITLE
browser_adapter.js: EXCEPTION: SyntaxError: Unexpected token A in JSON at position 0

### ISSUE THREAD

**Issue by jcramer** [auth0/auth0-angular2#22]
When I run this example using either webpack or systemjs I get the error above whenever I attempt to reach out to the api urls /ping or /secured/ping.  I have the node.js api server running and I was also getting an error.  Is anyone else having this issue?

I also found that the es6-shim needs to be bumped up to 0.34 or 0.35 in order to avoid a another error when starting up the angular app.

**Comment by chenkie** [comment]
Can you check with the latest updates and let me know if the issue is still there? Thanks :)

**Comment by jcramer** [comment]
Works great, thanks!
