### ISSUE TITLE
Impersonation not working

### ISSUE THREAD

**Issue by ferredel** [auth0/auth0-angular2#25]
Hello.

I'm just trying to use the Impersonation but.... nothing happens.

I'm not even trying  by API, just going to the auth0 dashboard and coping the link so I finally get into 

http://mypage.com/#access_token=Xb...D&id_token=ey..................yo&token_type=Bearer

Anyone else having this issue, or just something form my config has fucked up?

PS: I'm using ng2 Web-pack-starter.

**Comment by ferredel** [comment]
Any update on this ?

**Comment by chenkie** [comment]
Looking into this :)
